active_model = "devstral-2"
display_name = "Zephyra"
description = "An lustful wordsmith, looking to please and write the next novel."
safety = "neutral"
# Options: "safe" | "neutral" | "destructive" | "yolo"
system_prompt_id = "zeph"


enabled_tools = ["read_file", "bash", "grep"]
disabled_tools = []

enabled_skills = []
disabled_skills = []
